In [384]:
!pip install pandas

Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (2.1.1)
Requirement already satisfied: numpy>=1.23.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (1.24.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [385]:
import pandas as pd

In [386]:
df = pd.read_csv('./work/user_actions.csv')

In [387]:
df

       user_id event_type           event_time
0         1000       view  2024-05-01 00:34:01
1         1000      click  2024-05-01 00:34:18
2         1000      click  2024-05-01 00:35:41
3         1000      click  2024-05-01 00:36:42
4         1000       view  2024-05-01 00:40:01
...        ...        ...                  ...
17930     1299       view  2024-05-05 23:07:48
17931     1299      click  2024-05-06 05:50:19
17932     1299       view  2024-05-06 05:52:43
17933     1299      click  2024-05-06 05:55:32
17934     1299       view  2024-05-06 05:56:50

[17935 rows x 3 columns]

In [388]:
#view_count
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17935 entries, 0 to 17934
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     17935 non-null  int64
 1   event_type  17935 non-null  object
 2   event_time  17935 non-null  object
dtypes: int64(1), object(2)
memory usage: 420.5+ KB

In [389]:
df['event_time'] = pd.to_datetime(df['event_time'])

In [390]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17935 entries, 0 to 17934
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     17935 non-null  int64
 1   event_type  17935 non-null  object
 2   event_time  17935 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 420.5+ KB

In [391]:
df.groupby('user_id')['event_type'].agg(enent_type='count')

         enent_type
user_id
1000             81
1001             64
1002             54
1003             68
1004             76
...             ...
1295             42
1296             22
1297             29
1298             26
1299             33

[300 rows x 1 columns]

In [392]:
# Количество view, click, purchase
df_2 = df.groupby('user_id').agg( \
                        count_click=('event_type', lambda x: (x=='click').sum()), \
                        count_view=(('event_type'), lambda x: (x=='view').sum()), \
                        count_purchase=(('event_type'), lambda x: (x=='purchase').sum()) \
).reset_index()

df_2

     user_id  count_click  count_view  count_purchase
0       1000           23          50               8
1       1001           18          41               5
2       1002           16          35               3
3       1003           21          40               7
4       1004           30          36              10
..       ...          ...         ...             ...
295     1295           11          23               8
296     1296            9          11               2
297     1297           13          15               1
298     1298           11          12               3
299     1299           12          19               2

[300 rows x 4 columns]

In [393]:
#Также можно реализовать при помощи
new_df = df[['user_id', 'event_type']]

In [394]:
new_df

       user_id event_type
0         1000       view
1         1000      click
2         1000      click
3         1000      click
4         1000       view
...        ...        ...
17930     1299       view
17931     1299      click
17932     1299       view
17933     1299      click
17934     1299       view

[17935 rows x 2 columns]

In [395]:
pivot_new_df = new_df.pivot_table(
    index='user_id', 
    columns='event_type',
    aggfunc='size',
    fill_value=0 
).reset_index()

In [396]:
# pivot_new_df.columns.name = None
pivot_new_df

event_type  user_id  click  purchase  view
0              1000     23         8    50
1              1001     18         5    41
2              1002     16         3    35
3              1003     21         7    40
4              1004     30        10    36
..              ...    ...       ...   ...
295            1295     11         8    23
296            1296      9         2    11
297            1297     13         1    15
298            1298     11         3    12
299            1299     12         2    19

[300 rows x 4 columns]

In [326]:
# Средний интервал между действиями каждого пользователя
df

       user_id event_type          event_time
0         1000       view 2024-05-01 00:34:01
1         1000      click 2024-05-01 00:34:18
2         1000      click 2024-05-01 00:35:41
3         1000      click 2024-05-01 00:36:42
4         1000       view 2024-05-01 00:40:01
...        ...        ...                 ...
17930     1299       view 2024-05-05 23:07:48
17931     1299      click 2024-05-06 05:50:19
17932     1299       view 2024-05-06 05:52:43
17933     1299      click 2024-05-06 05:55:32
17934     1299       view 2024-05-06 05:56:50

[17935 rows x 3 columns]

In [344]:
df_avg = df.sort_values(['user_id', 'event_time'])

In [345]:
df_avg['avg'] = df.groupby('user_id')['event_time'].diff()

In [346]:
df_avg_user = df_avg.groupby('user_id')['avg'].mean().reset_index()

In [347]:
df_avg_user

     user_id                       avg
0       1000    0 days 02:04:40.975000
1       1001 0 days 02:28:39.698412698
2       1002 0 days 02:24:32.396226415
3       1003 0 days 02:12:15.641791044
4       1004 0 days 02:11:59.253333333
..       ...                       ...
295     1295 0 days 03:24:53.878048780
296     1296 0 days 05:00:36.380952380
297     1297 0 days 04:48:00.071428571
298     1298    0 days 03:35:08.240000
299     1299    0 days 03:25:14.687500

[300 rows x 2 columns]

In [348]:
# Время первой и последней активности
df_first_event = df.sort_values(['user_id', 'event_time'])

In [350]:
#first_event
df_first_event = df_first_event.groupby('user_id')['event_time'].min().reset_index()

In [367]:
df_first_event.columns = ['user_id', 'first_event']
df_first_event

     user_id         first_event
0       1000 2024-05-01 00:34:01
1       1001 2024-05-01 00:15:13
2       1002 2024-05-02 10:25:18
3       1003 2024-05-01 17:41:24
4       1004 2024-05-01 00:07:54
..       ...                 ...
295     1295 2024-05-02 01:17:54
296     1296 2024-05-01 16:35:11
297     1297 2024-05-01 13:18:01
298     1298 2024-05-02 17:16:25
299     1299 2024-05-01 16:29:00

[300 rows x 2 columns]

In [358]:
#last_event
df_last_event = df.sort_values(['user_id', 'event_time'])

In [359]:
df_last_event = df_last_event.groupby('user_id')['event_time'].max().reset_index()

In [365]:
df_last_event.columns = ['user_id', 'last_event']

In [366]:
df_last_event

     user_id          last_event
0       1000 2024-05-07 22:48:39
1       1001 2024-05-07 12:20:54
2       1002 2024-05-07 18:05:55
3       1003 2024-05-07 21:22:52
4       1004 2024-05-07 21:06:58
..       ...                 ...
295     1295 2024-05-07 21:18:43
296     1296 2024-05-06 01:47:55
297     1297 2024-05-07 03:42:03
298     1298 2024-05-06 10:54:51
299     1299 2024-05-06 05:56:50

[300 rows x 2 columns]

In [368]:
# Создание таблицы

In [376]:
user_report = df_2.join(df_avg_user['avg'])

In [378]:
user_report = user_report.join(df_first_event['first_event'])

In [380]:
user_report = user_report.join(df_last_event['last_event'])

In [381]:
user_report

,user_id,count_click,count_view,count_purchase,avg,first_event,last_event
0,1000,23,50,8,0 days 02:04:40.975000,2024-05-01 00:34:01,2024-05-07 22:48:39
1,1001,18,41,5,0 days 02:28:39.698412698,2024-05-01 00:15:13,2024-05-07 12:20:54
2,1002,16,35,3,0 days 02:24:32.396226415,2024-05-02 10:25:18,2024-05-07 18:05:55
3,1003,21,40,7,0 days 02:12:15.641791044,2024-05-01 17:41:24,2024-05-07 21:22:52
4,1004,30,36,10,0 days 02:11:59.253333333,2024-05-01 00:07:54,2024-05-07 21:06:58
...,...,...,...,...,...,...,...
295,1295,11,23,8,0 days 03:24:53.878048780,2024-05-02 01:17:54,2024-05-07 21:18:43
296,1296,9,11,2,0 days 05:00:36.380952380,2024-05-01 16:35:11,2024-05-06 01:47:55
297,1297,13,15,1,0 days 04:48:00.071428571,2024-05-01 13:18:01,2024-05-07 03:42:03
298,1298,11,12,3,0 days 03:35:08.240000,2024-05-02 17:16:25,2024-05-06 10:54:51
299,1299,12,19,2,0 days 03:25:14.687500,2024-05-01 16:29:00,2024-05-06 05:56:50

In [382]:
#Сохраняем таблицу

In [383]:
user_report.to_csv('user_report.csv', sep=',', index=False)